[theme]
base = "light"
primaryColor = "#672146"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F5F6"
textColor = "#445063"
linkColor = "#AC145A"
font = "sans-serif"
headingFont = "sans-serif"
baseFontSize = 16
baseFontWeight = 400
baseRadius = "small"
buttonRadius = "small"
borderColor = "#D0D3D4"
showWidgetBorder = true

[client]
toolbarMode = "minimal"
